### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Abdulsamipy** [James-Charles-Robinson/instagram-bot#1]
hi, so I was testing the bot it seems to be working fine, can you kindly add follow target user follower feature?

**Comment by James-Charles-Robinson** [comment]
Yes, of course, I will add that now. Give me a few hours.

**Comment by James-Charles-Robinson** [comment]
> hi, so I was testing the bot it seems to be working fine, can you kindly add follow target user follower feature?

Yes, of course, I will add that now. Although I'm not 100% sure exactly what you are asking I presume you mean to follow users from a text file?
Edit: Ok added, is that ok for you. Thanks for commenting tho, appreciate it.
